"""
Contact Form API - Generated by Johnie (Backend Developer Agent)

This module implements a Flask REST API for handling contact form submissions.
Includes input validation, error handling, and proper HTTP responses.
"""

from flask import Flask, request, jsonify
from pydantic import BaseModel, EmailStr, ValidationError, validator
from typing import Optional
import logging
from datetime import datetime

# Initialize Flask app
app = Flask(__name__)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ContactSubmission(BaseModel):
    """
    Contact form submission model with validation
    
    Attributes:
        name: Full name of the person submitting the form
        email: Valid email address
        subject: Subject line for the message
        message: The actual message content (min 10 characters)
    """
    name: str
    email: EmailStr
    subject: str
    message: str
    
    class Config:
        # Ensure minimum length for all string fields
        min_anystr_length = 1
    
    @validator('message')
    def message_must_be_long_enough(cls, v):
        """Validate message is at least 10 characters"""
        if len(v) < 10:
            raise ValueError('Message must be at least 10 characters')
        return v


@app.route('/health', methods=['GET'])
def health():
    """
    Health check endpoint
    
    Returns:
        JSON response with status and timestamp
    """
    return jsonify({
        "status": "healthy",
        "timestamp": datetime.now().isoformat(),
        "service": "Contact Form API"
    }), 200


@app.route('/contact', methods=['POST'])
def submit_contact():
    """
    Submit a contact form
    
    Request Body (JSON):
        {
            "name": "John Doe",
            "email": "john@example.com",
            "subject": "Question about services",
            "message": "I would like to know more about..."
        }
    
    Returns:
        201: Contact submitted successfully
            {
                "message": "Contact form submitted successfully",
                "id": "unique-submission-id",
                "submitted_at": "2025-01-03T23:59:00"
            }
        
        400: Validation error
            {
                "error": [
                    {"loc": ["email"], "msg": "invalid email format", "type": "value_error"}
                ]
            }
        
        500: Server error
            {
                "error": "Internal server error"
            }
    """
    try:
        # Validate request data using Pydantic
        data = ContactSubmission(**request.json)
        
        # Log the submission (in production: save to database)
        logger.info(
            f"Contact submission received - "
            f"From: {data.name} <{data.email}>, "
            f"Subject: {data.subject}"
        )
        
        # In a real application, you would:
        # 1. Save to database
        # 2. Send email notification
        # 3. Return actual submission ID
        
        submission_id = f"sub-{datetime.now().timestamp()}"
        
        # Return success response
        return jsonify({
            "message": "Contact form submitted successfully",
            "id": submission_id,
            "submitted_at": datetime.now().isoformat()
        }), 201
        
    except ValidationError as e:
        # Validation error - return detailed error messages
        logger.warning(f"Validation error: {e.errors()}")
        return jsonify({
            "error": e.errors()
        }), 400
        
    except Exception as e:
        # Unexpected error - log and return generic message
        logger.error(f"Unexpected error processing contact: {str(e)}", exc_info=True)
        return jsonify({
            "error": "Internal server error"
        }), 500


@app.route('/contact', methods=['OPTIONS'])
def contact_options():
    """
    Handle CORS preflight requests
    """
    return '', 204


@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors"""
    return jsonify({
        "error": "Endpoint not found"
    }), 404


@app.errorhandler(405)
def method_not_allowed(error):
    """Handle 405 errors"""
    return jsonify({
        "error": "Method not allowed"
    }), 405


if __name__ == '__main__':
    # Development server
    # In production, use a proper WSGI server like gunicorn
    app.run(
        debug=True,
        host='0.0.0.0',
        port=5000
    )

