"""
Test Suite for Contact Form API
Generated by Linda (Test Engineer Agent)

This module contains comprehensive tests for the contact form API,
including happy paths, validation errors, and edge cases.

Run with: pytest tests/test_api.py -v --cov=src
"""

import pytest
from src.app import app
import json


@pytest.fixture
def client():
    """
    Create a test client for the Flask app
    
    Yields:
        FlaskClient: Test client for making requests
    """
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client


class TestHealthEndpoint:
    """Tests for the health check endpoint"""
    
    def test_health_endpoint_returns_200(self, client):
        """Test that health endpoint returns 200 OK"""
        response = client.get('/health')
        assert response.status_code == 200
    
    def test_health_endpoint_returns_json(self, client):
        """Test that health endpoint returns valid JSON"""
        response = client.get('/health')
        data = response.get_json()
        assert data is not None
        assert 'status' in data
        assert data['status'] == 'healthy'
    
    def test_health_endpoint_includes_timestamp(self, client):
        """Test that health response includes timestamp"""
        response = client.get('/health')
        data = response.get_json()
        assert 'timestamp' in data
        assert 'service' in data


class TestContactSubmissionSuccess:
    """Tests for successful contact form submissions"""
    
    def test_valid_submission_returns_201(self, client):
        """Test that valid submission returns 201 Created"""
        data = {
            "name": "John Doe",
            "email": "john@example.com",
            "subject": "Test Subject",
            "message": "This is a test message with more than 10 characters"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 201
    
    def test_valid_submission_returns_submission_id(self, client):
        """Test that response includes submission ID"""
        data = {
            "name": "Jane Smith",
            "email": "jane@example.com",
            "subject": "Question",
            "message": "I have a question about your services"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        response_data = response.get_json()
        assert 'id' in response_data
        assert response_data['id'] is not None
    
    def test_valid_submission_returns_timestamp(self, client):
        """Test that response includes submission timestamp"""
        data = {
            "name": "Bob Johnson",
            "email": "bob@test.com",
            "subject": "Feedback",
            "message": "Great service, thank you very much!"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        response_data = response.get_json()
        assert 'submitted_at' in response_data
    
    def test_submission_with_special_characters(self, client):
        """Test that submission handles special characters"""
        data = {
            "name": "François José",
            "email": "francois@example.fr",
            "subject": "Spëcial Çhars",
            "message": "Testing with émojis 🎉 and spëcial çharacters!"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 201


class TestContactSubmissionValidation:
    """Tests for input validation errors"""
    
    def test_missing_all_fields_returns_400(self, client):
        """Test that missing all fields returns 400"""
        response = client.post(
            '/contact',
            data=json.dumps({}),
            content_type='application/json'
        )
        assert response.status_code == 400
    
    def test_missing_name_returns_400(self, client):
        """Test that missing name field returns 400"""
        data = {
            "email": "test@example.com",
            "subject": "Test",
            "message": "Test message here"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 400
    
    def test_missing_email_returns_400(self, client):
        """Test that missing email field returns 400"""
        data = {
            "name": "John Doe",
            "subject": "Test",
            "message": "Test message here"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 400
    
    def test_missing_subject_returns_400(self, client):
        """Test that missing subject field returns 400"""
        data = {
            "name": "John Doe",
            "email": "john@example.com",
            "message": "Test message here"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 400
    
    def test_missing_message_returns_400(self, client):
        """Test that missing message field returns 400"""
        data = {
            "name": "John Doe",
            "email": "john@example.com",
            "subject": "Test Subject"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 400
    
    def test_invalid_email_format_returns_400(self, client):
        """Test that invalid email format returns 400"""
        data = {
            "name": "John Doe",
            "email": "not-an-email",
            "subject": "Test",
            "message": "Test message with enough characters"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 400
    
    def test_message_too_short_returns_400(self, client):
        """Test that message shorter than 10 chars returns 400"""
        data = {
            "name": "John Doe",
            "email": "john@example.com",
            "subject": "Test",
            "message": "Short"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 400
    
    def test_empty_string_fields_return_400(self, client):
        """Test that empty string fields return 400"""
        data = {
            "name": "",
            "email": "john@example.com",
            "subject": "Test",
            "message": "Valid message here"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 400


class TestContactEdgeCases:
    """Tests for edge cases and boundary conditions"""
    
    def test_message_exactly_10_characters(self, client):
        """Test that message with exactly 10 chars is accepted"""
        data = {
            "name": "Test User",
            "email": "test@example.com",
            "subject": "Test",
            "message": "1234567890"  # Exactly 10 characters
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 201
    
    def test_very_long_message(self, client):
        """Test that very long messages are handled"""
        data = {
            "name": "Test User",
            "email": "test@example.com",
            "subject": "Long message test",
            "message": "A" * 10000  # Very long message
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        # Should either accept or return specific error
        assert response.status_code in [201, 400]
    
    def test_unicode_email_address(self, client):
        """Test internationalized email addresses"""
        data = {
            "name": "测试用户",
            "email": "test@example.com",  # ASCII email required by EmailStr
            "subject": "Unicode test",
            "message": "Testing with unicode characters: 你好世界"
        }
        response = client.post(
            '/contact',
            data=json.dumps(data),
            content_type='application/json'
        )
        assert response.status_code == 201


class TestErrorHandling:
    """Tests for error handling"""
    
    def test_invalid_json_returns_error(self, client):
        """Test that invalid JSON returns an error"""
        response = client.post(
            '/contact',
            data='{"invalid": json}',
            content_type='application/json'
        )
        assert response.status_code in [400, 500]
    
    def test_wrong_content_type_returns_error(self, client):
        """Test that wrong content type is handled"""
        response = client.post(
            '/contact',
            data='name=John&email=test@example.com',
            content_type='application/x-www-form-urlencoded'
        )
        assert response.status_code in [400, 500]
    
    def test_get_request_not_allowed(self, client):
        """Test that GET requests to /contact are not allowed"""
        response = client.get('/contact')
        assert response.status_code == 405
    
    def test_put_request_not_allowed(self, client):
        """Test that PUT requests to /contact are not allowed"""
        response = client.put('/contact')
        assert response.status_code == 405


class TestCORS:
    """Tests for CORS handling"""
    
    def test_options_request_returns_204(self, client):
        """Test that OPTIONS request returns 204"""
        response = client.options('/contact')
        assert response.status_code == 204


class TestNotFound:
    """Tests for 404 handling"""
    
    def test_invalid_endpoint_returns_404(self, client):
        """Test that invalid endpoints return 404"""
        response = client.get('/invalid-endpoint')
        assert response.status_code == 404
    
    def test_404_returns_json(self, client):
        """Test that 404 response is JSON"""
        response = client.get('/nonexistent')
        data = response.get_json()
        assert data is not None
        assert 'error' in data


# Test coverage summary:
# - Health endpoint: 3 tests
# - Successful submissions: 4 tests
# - Validation errors: 8 tests
# - Edge cases: 3 tests
# - Error handling: 4 tests
# - CORS: 1 test
# - 404 handling: 2 tests
# Total: 25 test cases

# Expected coverage: ~85-90%
# Missing coverage: Exception handling branches, logging statements

